import type { IssueReport } from './types';

export const mockIssues: IssueReport[] = [
  {
    id: '1',
    citizenId: 'user-123',
    category: 'Pothole',
    summary: 'Large pothole on arterial road in Koramangala.',
    description: 'There is a large and dangerous pothole on the main road in Koramangala 5th Block. It has already caused damage to vehicles.',
    location: {
      latitude: 12.9352,
      longitude: 77.6245,
      address: 'Koramangala 5th Block, Bengaluru',
    },
    imageUrl: 'https://picsum.photos/seed/pothole/600/400',
    imageHint: 'pothole road',
    status: 'Submitted',
    department: 'BBMP (Public Works)',
    createdAt: new Date('2024-07-20T10:00:00Z'),
    updatedAt: new Date('2024-07-20T10:00:00Z'),
  },
  {
    id: '2',
    citizenId: 'user-456',
    category: 'Broken Streetlight',
    summary: 'Streetlight not working in residential colony.',
    description: 'The streetlight near the park in Sector 15, Noida has been out for a week. It is very dark and feels unsafe at night.',
    location: {
      latitude: 28.583,
      longitude: 77.315,
      address: 'Sector 15, Noida',
    },
    imageUrl: 'https://picsum.photos/seed/streetlight/600/400',
    imageHint: 'broken streetlight',
    status: 'Acknowledged',
    department: 'Noida Authority (Electrical)',
    createdAt: new Date('2024-07-19T15:30:00Z'),
    updatedAt: new Date('2024-07-20T09:00:00Z'),
  },
  {
    id: '3',
    citizenId: 'user-789',
    category: 'Garbage',
    summary: 'Garbage dump not cleared for days.',
    description: 'The public garbage collection point at Juhu Circle is overflowing. It is a health hazard and smells terrible.',
    location: {
      latitude: 19.1076,
      longitude: 72.8273,
      address: 'Juhu Circle, Mumbai',
    },
    imageUrl: 'https://picsum.photos/seed/garbage/600/400',
    imageHint: 'overflowing garbage',
    status: 'In Progress',
    department: 'MCGM (Solid Waste Mgmt)',
    createdAt: new Date('2024-07-18T11:00:00Z'),
    updatedAt: new Date('2024-07-19T14:00:00Z'),
  },
  {
    id: '4',
    citizenId: 'user-123',
    category: 'Water Logging',
    summary: 'Severe water logging after rain.',
    description: 'The underpass near Minto Road is completely flooded after the recent rains, causing massive traffic jams.',
    location: {
      latitude: 28.633,
      longitude: 77.227,
      address: 'Minto Road, New Delhi',
    },
    imageUrl: 'https://picsum.photos/seed/flooding/600/400',
    imageHint: 'flooded street',
    status: 'Resolved',
    department: 'Delhi PWD',
    createdAt: new Date('2024-07-15T08:00:00Z'),
    updatedAt: new Date('2024-07-16T12:00:00Z'),
  },
];
